<?php

namespace App\Form;

use App\Entity\Brands;
use App\Entity\SneakerFilter;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SneakerFilterType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $choices = [];
        $value = 38.0;

        while ($value <= 47.0) {
            $choices[sprintf('%.1f', $value)] = $value;
            $value += 0.5;
        }


        $builder
            ->add('brands', EntityType::class, [
                'label' => false,
                'required' => false,
                'class'=>Brands::class,
                'choice_label'=>'name',
                'multiple'=>true,
                'expanded' => true,


            ])
            ->add('size', ChoiceType::class, [
                'label' => false,
                'required' => false,
                'expanded' => true,
                'choices' => $choices,
                'placeholder' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => SneakerFilter::class,
            'method' => 'get',
            'csrf_protection' => false
        ]);
    }

    public function getBlockPrefix()
    {
//        return parent::getBlockPrefix(); // TODO: Change the autogenerated stub
        return '';
    }

}
